### ISSUE TITLE
./waf configure shows error on Ubuntu 20.04

### ISSUE THREAD

**Issue by BCaran** [resibots/libdynamixel#66]
When I run:
`./waf configure --boost-libs /path/to/boost-libraries` I get the following error, please help!

Setting top to                           : /home/branimir/Downloads/libdynamixel-master 
Setting out to                           : /home/branimir/Downloads/libdynamixel-master/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking boost includes                  : 1_71 
Checking boost libs                      : Traceback (most recent call last):
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 171, in run_commands
    ctx=run_command(cmd_name)
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 162, in run_command
    ctx.execute()
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Configure.py", line 87, in execute
    super(ConfigurationContext,self).execute()
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/branimir/Downloads/libdynamixel-master/wscript", line 28, in configure
    conf.recurse('src/tools')
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/branimir/Downloads/libdynamixel-master/src/tools/wscript", line 10, in configure
    conf.check_boost(lib='program_options', min_version='1.39')
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Configure.py", line 184, in fun
    return f(*k,**kw)
  File "./waf_tools/boost.py", line 265, in check_boost
    path, libs = self.boost_get_libs(**params)
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Configure.py", line 184, in fun
    return f(*k,**kw)
  File "./waf_tools/boost.py", line 190, in boost_get_libs
    path, files = self.__boost_get_libs_path(**kw)
  File "/home/branimir/Downloads/libdynamixel-master/.waf-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Configure.py", line 184, in fun
    return f(*k,**kw)
  File "./waf_tools/boost.py", line 159, in __boost_get_libs_path
    files = path.ant_glob('*boost_*')
AttributeError: 'NoneType' object has no attribute 'ant_glob'

**Comment by jbmouret** [comment]
Thank you for your feedback. Honestly, we are not using this code right now and it probably need some refreshing / testing on modern systems, and I do not have the time for this right now.

Except if you need something very special, you should probably use the official dynamixel library by Robotis (it did not exist when we started this project). https://github.com/ROBOTIS-GIT/DynamixelSDK
(I would say that our library is better, but they have more ressources for the maintenance...).

**Comment by BCaran** [comment]
Thank you for your comment. 
I would probably use DynamixelSDK or dynamixel_interface for my project.

**Comment by costashatz** [comment]
If I may add, the issue you are describing is most probably coming from an old version of the `waf` executable. In case you really want to use our library, you can try downloading a newer version of waf ([here](https://waf.io/)) and retry.

**Comment by BCaran** [comment]
Hi @costashatz, I downloaded new waf, and error is same...

**Comment by costashatz** [comment]
Thanks for the update. I will try to use the library in the coming weeks and possibly attempt to fix the problem.. For the time being, I would suggest to follow @jbmouret 's advice and use the official repo for now..
